### ISSUE TITLE
Error compiling include_juce_gui_basics.cpp

### ISSUE THREAD

**Issue by WangElectronics** [centuryglass/PocketCHIP-pocket-home#2]
I get this error when trying to make.

>➜  Pocket-Home-Bismuth git:(master) make        
      Compiling: include_juce_gui_basics.cpp
In file included from deps/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp:186:0,
                 from JuceLibraryCode/include_juce_gui_basics.cpp:9:
deps/JUCE/modules/juce_gui_basics/filebrowser/juce_DirectoryContentsList.cpp: In member function 'bool juce::DirectoryContentsList::addFile(const juce::File&, bool, juce::int64, juce::Time, juce::Time, bool)':
deps/JUCE/modules/juce_gui_basics/filebrowser/juce_DirectoryContentsList.cpp:243:48: error: call of overloaded 'make_unique()' is ambiguous
         auto info = std::make_unique<FileInfo>();
                                                ^
deps/JUCE/modules/juce_gui_basics/filebrowser/juce_DirectoryContentsList.cpp:243:48: note: candidates are:
In file included from /usr/include/c++/4.9/memory:81:0,
                 from deps/JUCE/modules/juce_core/system/juce_StandardHeader.h:46,
                 from deps/JUCE/modules/juce_core/juce_core.h:201,
                 from deps/JUCE/modules/juce_graphics/juce_graphics.h:57,
                 from deps/JUCE/modules/juce_gui_basics/juce_gui_basics.h:57,
                 from deps/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp:45,
                 from JuceLibraryCode/include_juce_gui_basics.cpp:9:
/usr/include/c++/4.9/bits/unique_ptr.h:764:5: note: typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = juce::DirectoryContentsList::FileInfo; _Args = {}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<juce::DirectoryContentsList::FileInfo, std::default_delete<juce::DirectoryContentsList::FileInfo> >]
     make_unique(_Args&&... __args)
     ^
In file included from deps/JUCE/modules/juce_core/system/juce_StandardHeader.h:59:0,
                 from deps/JUCE/modules/juce_core/juce_core.h:201,
                 from deps/JUCE/modules/juce_graphics/juce_graphics.h:57,
                 from deps/JUCE/modules/juce_gui_basics/juce_gui_basics.h:57,
                 from deps/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp:45,
                 from JuceLibraryCode/include_juce_gui_basics.cpp:9:
deps/JUCE/modules/juce_core/system/juce_CompilerSupport.h:128:19: note: std::unique_ptr<_Tp> std::make_unique(Args&& ...) [with T = juce::DirectoryContentsList::FileInfo; Args = {}]
     unique_ptr<T> make_unique (Args&&... args)
                   ^
Makefile:281: recipe for target 'build/intermediate/Release/juce_gui_basics.o' failed
make: *** [build/intermediate/Release/juce_gui_basics.o] Error 1

**Comment by centuryglass** [comment]
This is due to [JUCE Issue #524](https://github.com/WeAreROLI/JUCE/issues/524).  The first few lines of the [main Makefile](https://github.com/centuryglass/Pocket-Home-Bismuth/blob/master/Makefile) are a temporary fix for this issue, but this must have failed somehow.  As a temporary fix, manually replace relevant (or all) instances of "201402L" with "201300L" in deps/JUCE/modules/juce_core/system/juce_StandardHeader.h, or otherwise ensure that `JUCE_CXX14_IS_AVAILABLE` is set to true within that file.

As a more permanent fix, I am attempting to migrate the project to the development branch of the JUCE library, where issue #524 has already been fixed.  However, other JUCE development branch changes break other things in my project, so I don't know how long it will take to finish this.

**Comment by WangElectronics** [comment]
Thanx 4 the quick reply! I will try this! :)

**Comment by WangElectronics** [comment]
I can't find any of the things you are suggesting. No 201402L in any file or the JUCE_CXX-thing... tried

grep -rnw '/home/chip/Pocket-Home-Bismuth/' -e 'JUCE_CXX14' etc.

**Comment by centuryglass** [comment]
Sorry I missed your reply, looks like I accidentally gave you the wrong file name too.
The file you need to change should be at Pocket-Home-Bismuth/deps/JUCE/modules/juce_core/system/juce_CompilerSupport.h .   You need to update line 53, ` #define JUCE_CXX14_IS_AVAILABLE (__cplusplus >= 201402L)`, replacing 201402L with 201300L.
