### ISSUE TITLE
How to update to latest version 

### ISSUE THREAD

**Issue by Cralex** [centuryglass/PocketCHIP-pocket-home#3]
I’m planning on selling my PocketCHIP and installing Bismuth on it beforehand, since it seems to be the most mature and friendly alternative to Pocket-Home available, and since it is still in development. My question is, is there an easy way to update to the next stable release when it comes out? I would hope that whoever buys my unit is somewhat Linux savvy, but you never know. Thanks!

**Comment by centuryglass** [comment]
Whenever a new release comes out I'll update the download link on the [installation instruction page](https://github.com/centuryglass/Pocket-Home-Bismuth/blob/master/docs/BuildAndInstall.md), reinstalling it by following the first two steps on that page will be the easiest way to update.

At some point I should probably set up a proper Debian package repository to handle updates, but unfortunately it will probably be a while before I start work on this project again.
