### ISSUE TITLE
menu frame removal

### ISSUE THREAD

**Issue by bberry1413** [centuryglass/PocketCHIP-pocket-home#4]
I tried to remove the bit of code calling the frame around the desktop in the ImageAssets.json file and with a reboot PocketChip is hung up on welcome screen. Any idea how to safely do this? I love your pocket home but I really don't care for the brown and pink frame on the desktop. That's my ONLY gripe.

**Comment by centuryglass** [comment]
I'd have to see your imageAssets.json file to know for sure, but the most likely problem is that you forgot to delete a bracket or something, and your imageAssets.json file is no longer valid JSON.  If you delete imageAssets.json before launching it again, it will recreate the file and it should work again.

Removing the entire "menu frame" section from imageAssets wouldn't work anyway.  If Bismuth can't find a section it expects in the file, it will recreate it from default settings. Instead, remove the image path, changing the menu frame section from this:

```
"menu frame": {
    "image files": [
      "component assets/MenuFrame/frame.svg"
    ],
    "colours": [
      "ffb88e47",
      "ffb8b8b8"
    ]
  },
```
to this:
```
"menu frame": {
    "image files": [],
    "colours": [
      "ffb88e47",
      "ffb8b8b8"
    ]
  },
```
(You can safely replace "colours" with an empty list as well, but without the image path it makes no difference what they're set to anyway.)

**Comment by bberry1413** [comment]
Dude you rock. Thanks!
